project:
  type: website
  output-dir: docs

website:
  title: "Kimberly Dominguez's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Projectpage.qmd
        text: STAT 244

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

